import React,{useEffect,useState}from'react';import{createRoot}from'react-dom/client';import{ADDRESS,EX,connect,read,wait,write}from'./genlayer.js';import'./style.css';import'./review-links.css';
const FIXTURE='cmrazrvph0am30rns9tzwb2oa',short=x=>x?`${String(x).slice(0,7)}…${String(x).slice(-5)}`:'—';
function App(){const[wallet,setWallet]=useState(null),[id,setId]=useState(FIXTURE),[chain,setChain]=useState('OP_MAINNET'),[item,setItem]=useState(null),[config,setConfig]=useState(null),[busy,setBusy]=useState(''),[notice,setNotice]=useState('Ready to inspect an official incident.');const url=`https://status.optimism.io/en-us/${id}`;
 const sync=async()=>{setBusy('sync');try{setConfig(await read('get_config'));setItem(await read('get_incident',[id]));setNotice('Authoritative state synchronized.')}catch(e){setItem(null);setNotice(e.message)}finally{setBusy('')}};useEffect(()=>{if(ADDRESS)read('get_config').then(setConfig).catch(e=>setNotice(e.message))},[]);
 const tx=async(fn,args)=>{if(!wallet)throw Error('Connect a wallet first.');setBusy(fn);try{const h=await write(wallet,fn,args);setNotice(`Submitted ${short(h)}`);await wait(h,s=>setNotice(`${fn}: ${s.label}`));await sync();setNotice(`${fn} accepted and state re-read.`)}catch(e){setNotice(e.message)}finally{setBusy('')}};
 const role=!wallet?'NOT CONNECTED':!item?'CAN REGISTER':wallet.account.toLowerCase()===String(item.reporter).toLowerCase()?'REPORTER':'INDEPENDENT VERIFIER';
 return <><header><div className="brand"><img src="/rollup-relief-logo.png"/><div><b>RollupRelief</b><span>Incident attestation registry</span></div></div><nav><a href="https://github.com/macdon3202/RollupRelief" target="_blank" rel="noreferrer">GitHub ↗</a><a href="https://github.com/macdon3202/RollupRelief/blob/main/docs/STUDIONET_V3_E2E.md" target="_blank" rel="noreferrer">E2E evidence ↗</a><a href={ADDRESS?`${EX}/address/${ADDRESS}`:'#'} target="_blank" rel="noreferrer">Contract ↗</a></nav><button onClick={async()=>{try{setWallet(await connect());setNotice('Wallet connected.')}catch(e){setNotice(e.message)}}}>{wallet?short(wallet.account):'Connect wallet'}</button></header><main>
 <section className="hero"><div><span className="kicker">OPTIMISM · OFFICIAL STATUS EVIDENCE</span><h1>Was the rollup really<br/><em>unable to accept writes?</em></h1><p>Convert official incident narratives into bounded, replay-protected attestations that deadline-sensitive Web3 apps can query.</p><div className="role"><span>Connected role</span><b>{role}</b></div></div><div className="mark"><img src="/rollup-relief-logo.png"/><span>Permissionless two-wallet verification</span></div></section>
 <section className="stats"><div><span>Network</span><b>Studionet</b></div><div><span>Authority</span><b>{config?.authority||'OPTIMISM_STATUS'}</b></div><div><span>Incidents</span><b>{config?.incident_count??'—'}</b></div><div><span>Contract</span><b>{ADDRESS?short(ADDRESS):'Pending deploy'}</b></div></section>
 <section className="work"><div className="panel"><span className="num">01 · INCIDENT INTAKE</span><h2>Bind the official notice</h2><label>Chain key<input value={chain} onChange={e=>setChain(e.target.value)}/></label><label>Incident ID<input value={id} onChange={e=>setId(e.target.value)}/></label><label>Canonical source<input readOnly value={url}/></label><button disabled={busy||!wallet||!!item} onClick={()=>tx('register_incident',[chain,id,url])}>Register this incident</button><button className="ghost" disabled={busy} onClick={sync}>Sync existing incident</button><small>Any wallet may register an unused canonical incident. That wallet becomes its reporter and cannot verify its own submission.</small></div>
 <div className="panel result"><div className="head"><div><span className="num">02 · CONSENSUS ATTESTATION</span><h2>Operational impact</h2></div><span className={`badge ${item?.state||''}`}>{item?.state||'NOT LOADED'}</span></div>{item?<><div className="impact"><article><span>Affected operation</span><b>{item.affected_operation||'PENDING'}</b></article><article><span>Impact</span><b>{item.impact_level||'PENDING'}</b></article><article className={item.qualifies_for_relief?'yes':'no'}><span>Relief eligibility</span><b>{item.qualifies_for_relief?'QUALIFIES':'DOES NOT QUALIFY'}</b></article></div><dl><dt>Reason code</dt><dd>{item.reason_code||'Awaiting assessment'}</dd><dt>Content digest</dt><dd>{item.content_digest||'Not sealed'}</dd><dt>Evidence bundle</dt><dd>{item.source_digest||'Not sealed'}</dd><dt>Revision</dt><dd>{String(item.revision)}</dd></dl><button disabled={busy||role!=='INDEPENDENT VERIFIER'||item.state!=='REGISTERED'} onClick={()=>tx('assess_incident',[id])}>Assess independently</button></>:<div className="empty">Register or sync an incident to reveal its attestation timeline.</div>}</div></section>
 <section className="method"><span className="num">03 · PROOF MODEL</span><h2>One official source.<br/>Any two independent wallets.</h2><div>{[['01','Bind','Exact Optimism origin and incident ID.'],['02','Fetch','Validators independently retrieve the page.'],['03','Classify','Consensus distinguishes write outage from maintenance.'],['04','Seal','Digest, outcome and revision become queryable state.']].map(x=><article key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section><section className="review-links"><div><span className="num">04 · REVIEW LINKS</span><h2>Verify the complete submission.</h2><p>Direct public links to the source, deployed contract, and transaction-level Studionet evidence.</p></div><div><a href="https://github.com/macdon3202/RollupRelief" target="_blank" rel="noreferrer"><b>Source repository</b><span>github.com/macdon3202/RollupRelief ↗</span></a><a href="https://github.com/macdon3202/RollupRelief/blob/main/docs/STUDIONET_V3_E2E.md" target="_blank" rel="noreferrer"><b>V3 E2E ledger</b><span>Happy, negative, conflict and adversarial paths ↗</span></a><a href={ADDRESS?`${EX}/address/${ADDRESS}`:'#'} target="_blank" rel="noreferrer"><b>Studionet contract</b><span>{ADDRESS||'Not configured'} ↗</span></a></div></section></main><footer><span>{notice}</span><span>{busy?'Working…':'Post-write readback required'}</span></footer></>}
createRoot(document.getElementById('root')).render(<App/>);
